import { StyleSheet } from '@react-pdf/renderer';

export const invoiceStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#333' },
  headerContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
  senderName: { fontSize: 24, fontWeight: 'bold', color: '#4C8BF5', width: '60%' },
  metaTable: { width: '35%' },
  metaRow: { flexDirection: 'row', borderBottom: '1pt solid #999', borderRight: '1pt solid #999', borderLeft: '1pt solid #999' },
  metaRowTop: { borderTop: '1pt solid #999' },
  metaLabel: { width: '40%', padding: 4, color: '#333' },
  metaValue: { width: '60%', padding: 4, fontWeight: 'bold', borderLeft: '1pt solid #999', textAlign: 'right' },
  metaValueBlue: { color: '#4C8BF5' },
  billToContainer: { marginBottom: 30 },
  billToTitle: { fontSize: 10, fontWeight: 'bold', color: '#1a365d', borderBottom: '1pt solid #ccc', paddingBottom: 2, marginBottom: 4, width: 200 },
  table: { width: '100%', border: '1pt solid #4C8BF5', borderBottom: 'none' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#4C8BF5', color: '#fff' },
  colDesc: { flex: 3, padding: 5, borderRight: '1pt solid #4C8BF5', fontWeight: 'bold' },
  colHours: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'center', fontWeight: 'bold' },
  colCost: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'center', fontWeight: 'bold' },
  colAmount: { flex: 1, padding: 5, textAlign: 'right', fontWeight: 'bold' },
  tableRow: { flexDirection: 'row', borderBottom: '1pt solid #4C8BF5' },
  tableRowSection: { flexDirection: 'row', borderBottom: '1pt solid #4C8BF5', backgroundColor: '#f0f5ff' },
  cellDesc: { flex: 3, padding: 5, borderRight: '1pt solid #4C8BF5' },
  cellHours: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'center' },
  cellCost: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'center' },
  cellAmount: { flex: 1, padding: 5, textAlign: 'right' },
  cellSection: { flex: 1, padding: 5, fontWeight: 'bold' },
  totalRow: { flexDirection: 'row', borderBottom: '1pt solid #4C8BF5' },
  totalLabel: { flex: 3, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'right', fontWeight: 'bold' },
  totalHours: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5', textAlign: 'center', fontWeight: 'bold' },
  totalAmountEmpty: { flex: 1, padding: 5, borderRight: '1pt solid #4C8BF5' },
  totalAmount: { flex: 1, padding: 5, textAlign: 'right', fontWeight: 'bold' },
  paymentContainer: { marginTop: 40 },
  paymentTitle: { fontWeight: 'bold', fontSize: 10, marginBottom: 10 },
  paymentRow: { flexDirection: 'row', marginBottom: 3 },
  paymentLabel: { width: 120, fontWeight: 'bold' },
  paymentValue: { flex: 1 }
});
