'use client'

import { useState, useEffect } from 'react'
import { Sparkles, Loader2, Database, AlertCircle } from 'lucide-react'

import { ExecutiveSummaryCard } from '@/components/analytics/ExecutiveSummaryCard'
import { ProfitAnalysisCard } from '@/components/analytics/ProfitAnalysisCard'
import { RevenueInsightsCard } from '@/components/analytics/RevenueInsightsCard'
import { ExpenseAnalysisCard } from '@/components/analytics/ExpenseAnalysisCard'
import { FXLossCard } from '@/components/analytics/FXLossCard'
import { CashflowCard } from '@/components/analytics/CashflowCard'
import { KeyMetricsCard } from '@/components/analytics/KeyMetricsCard'
import { RevenueAnalysisChart } from '@/components/analytics/RevenueAnalysisChart'
import { DollarRateAnalysisCard } from '@/components/analytics/DollarRateAnalysisCard'
import { RecommendationsCard } from '@/components/analytics/RecommendationsCard'
import { DateRangePicker, defaultDateRange, type DateRange } from '@/components/ui/DateRangePicker'
import { PageHeader } from '@/components/shared/PageHeader'

export default function AnalyticsPage() {
  const [dateRange, setDateRange] = useState<DateRange>(defaultDateRange)
  const [loadingInitial, setLoadingInitial] = useState(true)
  const [dataSummary, setDataSummary] = useState<any>(null)
  const [rawData, setRawData] = useState<any>(null)
  const [dollarAnalysis, setDollarAnalysis] = useState<string>('')

  const [analyzing, setAnalyzing] = useState(false)
  const [report, setReport] = useState<any>(null)
  const [error, setError] = useState('')

  useEffect(() => {
    setLoadingInitial(true)
    setReport(null)
    const params = new URLSearchParams({ startDate: dateRange.from, endDate: dateRange.to })
    fetch(`/api/analytics/data?${params}`)
      .then(res => res.json())
      .then(data => {
        if (data.summary) {
          setDataSummary(data.summary)
          setRawData(data.data)
        }
      })
      .catch(err => console.error(err))
      .finally(() => setLoadingInitial(false))
  }, [dateRange])

  const generateAnalysis = async () => {
    setAnalyzing(true)
    setError('')
    try {
      const res = await fetch('/api/analytics/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ payload: rawData, dateRange })
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed to generate analysis')
      setReport(data)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setAnalyzing(false)
    }
  }

  if (loadingInitial) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh]">
        <Loader2 className="w-8 h-8 text-indigo-500 animate-spin mb-4" />
        <p className="text-neutral-400">Aggregating ledger data...</p>
      </div>
    )
  }

  if (analyzing) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh]">
        <div className="relative">
          <div className="w-20 h-20 border-4 border-indigo-500/30 rounded-full animate-ping absolute inset-0"></div>
          <div className="w-20 h-20 bg-indigo-500/10 rounded-full flex items-center justify-center relative z-10 backdrop-blur-sm border border-indigo-500/30">
            <Sparkles className="w-10 h-10 text-indigo-400 animate-pulse" />
          </div>
        </div>
        <h2 className="text-2xl font-bold text-white mt-8 mb-2">Analyzing Ledger Data</h2>
        <p className="text-neutral-400 max-w-md text-center">
          Groq is crunching your invoices, expenses, settlements, and FX rates to build a comprehensive intelligence report. This usually takes 5-10 seconds.
        </p>
      </div>
    )
  }

  if (report) {
    return (
      <div className="space-y-6 pb-20">
        <PageHeader
          title="AI Financial Intelligence"
          subtitle="Generated by Llama 3 on Groq"
          actions={
            <>
              <DateRangePicker value={dateRange} onChange={setDateRange} />
              <button
                onClick={generateAnalysis}
                className="bg-neutral-800 hover:bg-neutral-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors whitespace-nowrap"
              >
                Regenerate
              </button>
            </>
          }
        />

        <div className="w-full">
          <ExecutiveSummaryCard {...report.executiveSummary} />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <KeyMetricsCard metrics={{ ...report.keyMetrics, ...report.executiveSummary?.metrics }} />
          <RevenueInsightsCard data={report.revenueInsights} />
        </div>

        <div className="w-full">
          <RevenueAnalysisChart rawData={rawData} onAnalysisReady={setDollarAnalysis} />
        </div>

        {dollarAnalysis && (
          <div className="w-full">
            <DollarRateAnalysisCard analysis={dollarAnalysis} />
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <ProfitAnalysisCard data={report.profitAnalysis} />
          <ExpenseAnalysisCard data={report.expenseAnalysis} />
          <FXLossCard data={report.fxLoss} />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <CashflowCard data={report.cashflow} />
          <RecommendationsCard recommendations={report.recommendations} />
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-8">
      <PageHeader
        title="AI Financial Intelligence"
        subtitle="Generate a deeply insightful, brutally honest, and actionable financial report powered by Groq & Llama 3."
        actions={<DateRangePicker value={dateRange} onChange={setDateRange} />}
      />

      {dataSummary && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
            <p className="text-neutral-500 text-xs uppercase tracking-wider mb-1">Invoices</p>
            <p className="text-xl font-bold text-white">{dataSummary.totalInvoices}</p>
            <p className="text-indigo-400 text-sm mt-1">${dataSummary.invoiceVolume?.toLocaleString()}</p>
          </div>
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
            <p className="text-neutral-500 text-xs uppercase tracking-wider mb-1">Expenses</p>
            <p className="text-xl font-bold text-white">{dataSummary.totalExpenses}</p>
            <p className="text-rose-400 text-sm mt-1">₹{dataSummary.expenseVolume?.toLocaleString()}</p>
          </div>
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
            <p className="text-neutral-500 text-xs uppercase tracking-wider mb-1">Settlements</p>
            <p className="text-xl font-bold text-white">{dataSummary.totalSettlements}</p>
          </div>
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
            <p className="text-neutral-500 text-xs uppercase tracking-wider mb-1">Accounts</p>
            <p className="text-xl font-bold text-white">{dataSummary.totalAccounts}</p>
          </div>
        </div>
      )}

      {error && (
        <div className="bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-xl p-4 flex items-center gap-2">
          <AlertCircle className="w-5 h-5 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className="flex justify-center pt-4">
        <button
          onClick={generateAnalysis}
          className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-4 rounded-xl text-lg font-medium transition-all hover:scale-105 active:scale-95 flex items-center gap-3"
        >
          <Database className="w-5 h-5" />
          Generate AI Analysis
        </button>
      </div>
    </div>
  )
}
